spring.application.name=Shopping-Cart
server.port=1010

spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:51487/railway?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=TypUVWKWOaqzKWKYbPWvUKqlJPzNZuoG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.allow-bean-definition-overriding=true
